// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://douealcovwsuarbytfuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvdWVhbGNvdndzdWFyYnl0ZnVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4OTc4MTYsImV4cCI6MjA2NjQ3MzgxNn0.1gMHp8MiVYyw7puuOyDnAT6SquI1bLBt13JxWZi2bt8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);